### ISSUE TITLE
Reconnecting Error

### ISSUE THREAD

**Issue by Loi83** [angelnu/ioBroker.chromecast#67]
Hallo ich habe immer öfter das Problem das mein GH Probleme macht. Anbei mal das Log.
Hello I have more often the problem that makes my GH problems. Attach the log.

`

chromecast.0 | 2019-11-23 11:37:56.707 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
-- | -- | -- | --
chromecast.0 | 2019-11-23 11:37:56.706 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:37:36.739 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:37:36.738 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:37:35.715 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:37:35.715 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:37:13.347 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:37:13.346 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:37:12.313 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:37:12.313 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:37:05.164 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:37:05.164 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:36:35.556 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:36:35.555 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:36:35.534 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:36:35.533 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:36:35.517 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:36:35.516 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:36:35.513 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:36:35.513 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:36:35.508 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:36:35.507 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:36:30.898 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:35:57.363 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:35:24.850 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:34:53.445 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:34:53.445 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:34:49.011 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:34:15.474 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:33:42.962 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:33:11.523 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:33:11.523 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:33:11.453 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:33:11.453 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:33:11.244 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:33:11.244 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:33:06.866 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:32:33.330 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:32:00.818 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:31:29.236 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:31:29.235 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:31:29.225 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:31:29.224 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:31:29.195 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:31:29.194 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:31:24.725 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:30:51.187 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:30:18.674 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:29:47.190 | info | (32653) Reconnecting Küche to 192.168.178.44:8009
chromecast.0 | 2019-11-23 11:29:47.189 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:29:47.165 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:29:47.164 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:29:18.770 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:29:18.770 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:28:47.293 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:28:47.292 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:28:47.282 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:28:47.281 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:28:47.265 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:28:47.264 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:28:47.259 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:28:47.258 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:28:47.213 | info | (32653) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:28:47.212 | info | (32653) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:28:43.186 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:28:43.186 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:28:09.651 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:28:09.651 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:27:37.140 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:27:37.140 | warn | (32653) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:27:05.932 | info | (32653) Bad - Connected client
chromecast.0 | 2019-11-23 11:27:04.827 | info | (32653) starting. Version 2.3.1 in /opt/iobroker/node_modules/iobroker.chromecast, node: v10.16.2
chromecast.0 | 2019-11-23 11:27:00.104 | info | (486) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
chromecast.0 | 2019-11-23 11:27:00.103 | info | (486) terminating
chromecast.0 | 2019-11-23 11:27:00.102 | info | (486) Unload completed sucesfully
chromecast.0 | 2019-11-23 11:27:00.102 | info | (486) Bad - client disconnected
chromecast.0 | 2019-11-23 11:27:00.099 | info | (486) Destroying chromecast scanner
chromecast.0 | 2019-11-23 11:27:00.098 | info | (486) Unload triggered
chromecast.0 | 2019-11-23 11:27:00.097 | info | (486) Got terminate signal TERMINATE_YOURSELF
chromecast.0 | 2019-11-23 11:26:57.714 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:26:57.714 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:26:30.455 | error | (486) Küche - undefined
chromecast.0 | 2019-11-23 11:26:26.311 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:26:26.310 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:26:26.151 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:26:26.151 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:26:21.622 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:26:21.622 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.44:8009
chromecast.0 | 2019-11-23 11:26:20.484 | error | (486) Küche - Cannot play file "http://192.168.178.xx:8082/vis.0/main/img/Big-ben-doorbell-sound.mp3": TypeError: Cannot read property 'stack' of undefined
chromecast.0 | 2019-11-23 11:26:20.473 | error | (486) Küche - undefined
chromecast.0 | 2019-11-23 11:26:20.455 | warn | (486) Küche - Waiting up to 10 seconds for connection to chromecast
chromecast.0 | 2019-11-23 11:26:10.564 | info | (486) Küche - Closing mediaInfo
chromecast.0 | 2019-11-23 11:26:10.483 | warn | (486) Küche - Waiting up to 10 seconds for connection to chromecast
chromecast.0 | 2019-11-23 11:26:10.480 | info | (486) Küche - Try to launch default player
chromecast.0 | 2019-11-23 11:26:10.477 | info | (486) Küche - Try to play url - http://192.168.178.xx:8082/vis.0/main/img/Big-ben-doorbell-sound.mp3
chromecast.0 | 2019-11-23 11:26:10.472 | warn | (486) Küche - Waiting up to 10 seconds for connection to chromecast
chromecast.0 | 2019-11-23 11:25:48.086 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:25:48.086 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:25:15.570 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:25:15.570 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:24:44.133 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:24:44.132 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:24:44.092 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:24:44.092 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:24:39.730 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:24:39.730 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:24:06.194 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:24:06.194 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:23:33.682 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:23:33.682 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:23:02.094 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:23:02.094 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:23:02.072 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:23:02.072 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:22:57.586 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:22:57.586 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:22:24.050 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:22:24.050 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:21:51.539 | warn | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
chromecast.0 | 2019-11-23 11:21:51.539 | warn | (486) Küche - Client error: Error: connect ETIMEDOUT 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:21:20.049 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:21:20.048 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:59.985 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:59.984 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:51.622 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:51.621 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:39.989 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:39.988 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:38.977 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:38.975 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:26.666 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:26.666 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:26.664 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:26.663 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:25.614 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:25.613 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:25.611 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:25.611 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:04.153 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:04.152 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:04.037 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:04.036 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:04.004 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:04.003 | info | (486) Received keep alive for disconnected device Küche
chromecast.0 | 2019-11-23 11:20:03.931 | info | (486) Reconnecting Küche to 192.168.178.xx:8009
chromecast.0 | 2019-11-23 11:20:03.930 | info | (486) Received keep alive for disconnected device Küche

`

**Comment by maxpd1** [comment]
Same here. Genau gleicher Log.

seit paar Wochen erkennt der Chromecast Adapter einen Google Home nicht mehr.
Es gab keine Updates oder Einstellungsänderurngen meinerseits auf Seiten Adapter oder Google Home.

IFTTT Antworten kommen auch noch auf dem Gerät an, aber keine mehr von iobroker.

Ich hab das Gerät schon aus dem Adapter gelöscht und mal umbenannt. Aber hilft nix.

**Comment by angelnu** [comment]
if you get the verbose logs we would be able to see more.

Unfortunately I am not longer using this adapter at my home so I can only help via logs. Long term is a challenge that the base library for node.js (https://github.com/thibauts/node-castv2-client#readme) is based on reverse engineering. So if Goggle changes the protocol in new devices it might break the existing code.

**Comment by maxpd1** [comment]
Its only a little bit curious that it only appears at one of three devices.
What are you now using?
How can I provide you with another log? This is everything I see now.

**Comment by maxpd1** [comment]
@angelnu 
which log do you exactly need? 
which adapter are you now using?
